  version: '3.8'

  services:

    sql-db:
      image: postgres:15.1
      container_name: best-travel
      restart: always
      volumes:
        - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
        - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
      environment:
        - POSTGRES_DB=best_travel
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
      ports:
        - "5432:5432"

    cache-db:
      depends_on:
        - sql-db
      image: redis:6.2-alpine
      container_name: best-travel-cache
      restart: always
      ports:
        - "6379:6379"
      command: redis-server --loglevel warning --requirepass root

    # ---- Docker command ----
    
    #
    # docker run \
    # --name best_travel_sql \
    # -p 5432:5432 \
    # -e POSTGRES_DB=best_travel \
    # -e POSTGRES_USER=alejandro \
    # -e POSTGRES_PASSWORD=debuggeandoideas \
    # -v ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql \
    # -v ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql postgres:latest
    #